CREATE TABLE Minions (
 Id INT IDENTITY,
 [Name] NVARCHAR(30) NOT NULL,
 Age SMALLINT
)

ALTER TABLE Minions
ADD CONSTRAINT PK_Minions PRIMARY KEY (Id)

CREATE TABLE Towns (
 Id INT IDENTITY,
 [Name] NVARCHAR(30) NOT NULL
)

ALTER TABLE Towns
ADD CONSTRAINT PK_Towns PRIMARY KEY (Id)